name: Update Canvas

on:    
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install github-to-canvas
        run: gem install github-to-canvas 
              
      - name: Checkout
        uses: actions/checkout@v3

      # Secret stored in learn-co-curriculum Settings/Secrets
      - name: Sync from .canvas file
        run: github-to-canvas -a -lr 
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
          CANVAS_API_PATH: ${{ secrets.CANVAS_API_PATH }}
