name: Curriculum Update Canvas Lessons

on:
  workflow_dispatch:

jobs:
  Test_remote_action:
    uses: learn-co-curriculum/dsc-github-actions-files/.github/workflows/github-to-canvas-sync.yml@<add version here>
    secrets: inherit