name: Curriculum Solution Branch Splitter

on:
  workflow_call:

jobs:
  build:

    runs-on: macos-latest

    steps:
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          check-latest: true
          
      - name: Install GitPython
        run: pip install GitPython
        
      - name: Install Jupyter Notebook
        run: pip install notebook
          
      - name: Check git version
        run: git --version
        
      - name: Checkout curriculum branch
        uses: actions/checkout@v3
        with:
          ref: curriculum
          token: ${{secrets.DS_ACTIONS_PAT}}
        
      - name: Checkout main/master branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{secrets.DS_ACTIONS_PAT}}

      - name: Checkout solution branch
        uses: actions/checkout@v3
        with:
          ref: solution
          token: ${{secrets.DS_ACTIONS_PAT}}
        continue-on-error: true
        
      - name: Checkout dsc-github-actions file repo
        uses: actions/checkout@v3
        with:
          repository: learn-co-curriculum/dsc-github-actions-files
          path: dsc-github-actions-files
          ref: ${{ github.event.repository.default_branch }}
          token: ${{secrets.DS_ACTIONS_PAT}}                              
          
      - name: Branch splitter sync (from dsc-github-actions-files repo)
        run: python dsc-github-actions-files/splitter.py  -m 'syncing changes across branches'
        
