name: Curriculum Solution Branch Splitter

on:
  workflow_call:

jobs:
  build:

    runs-on: macos-latest

    steps:
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          check-latest: true
          
      - name: Install GitPython
        run: pip install GitPython
        
      - name: Install Jupyter Notebook
        run: pip install notebook
          
      - name: Check git version
        run: git --version
        
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - uses: actions/checkout@v3
        with:
          ref: solution
        continue-on-error: true
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: curriculum
      
      #- name: Check-out devops repository
      #  uses: actions/checkout@v3
      #  with:
      #    repository: learn-co-curriculum/dsc-github-actions-files
      #    path: dsc-github-actions-files

      - name: Branch splitter sync
        run: python splitter.py  -m 'syncing changes across branches'
        
