name: Curriculum Solution Branch Splitter

on:
  workflow_call:

jobs:
  build:

    runs-on: macos-latest

    steps:
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          check-latest: true
          
      - name: Install GitPython
        run: pip install GitPython
        
      - name: Install Jupyter Notebook
        run: pip install notebook
          
      - name: Check git version
        run: git --version
        
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{secrets.DS_ACTIONS_PAT}}
          submodules: false

      - uses: actions/checkout@v3
        with:
          ref: solution
          token: ${{secrets.DS_ACTIONS_PAT}}
          submodules: false
        continue-on-error: true
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: curriculum
          token: ${{secrets.DS_ACTIONS_PAT}}
          submodules: false
          
      - name: Branch splitter sync
        run: python splitter.py  -m 'syncing changes across branches'
        
